language: java
sudo: required
dist: trusty
cache:
  directories:
  - $HOME/.m2/repository
services:
- docker
env:
  global:
  - DOCKER_REPO=$TRAVIS_REPO_SLUG
before_install:
- apt-cache madison docker-ce
- travis_retry sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script:
- jdk_switcher use oraclejdk8
- mvn test
- jdk_switcher use openjdk7
- mvn test
- travis_retry bin/build-release.sh
matrix:
  fast_finish: true
  include:
  - env: STORM_RELEASE="1.0.3" MESOS_RELEASE="1.1.0"
  - env: STORM_RELEASE="1.0.3" MESOS_RELEASE="0.28.2"
before_deploy:
- travis_retry make images
- travis_retry make images JAVA_PRODUCT_VERSION=8
- docker images
- travis_retry docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- travis_retry make push
- travis_retry make push JAVA_PRODUCT_VERSION=8
deploy:
  provider: releases
  api_key:
    secure: SEKAUlMBRXrm9EY8JUYKrXQYC7v1+nJ2/0H23KvcZGbvBL6tMaY1jPJZ8vlCJjCwd69WUCc9a1p/IzYMkt6jz4xx2vB13MYL7GnQgltzEwCAVl7I6uw1r08SDyNdeCeBqZFTcPXmrWM5ByQ0q/4SqEqLMw1uCTfOQV1/XQeivkA=
  file: "storm-mesos-$(grep -1 -A 0 -B 0 '<version>' pom.xml | head -n 1 | awk '{print $1}' | sed -e 's/.*<version>//' | sed -e 's|</version>.*||')-storm$STORM_RELEASE-mesos$MESOS_RELEASE.tgz"
  skip_cleanup: true
  on:
    tags: true
    repo: $TRAVIS_REPO_SLUG
